var app = getApp()
Page({
    data:{
      list:[
          {
              list_tool:[
                {
                    img:"../../image/newFriend.png",
                    name:"新的朋友",
                    url:"../newfriend/newfriend"
                },
                {
                    img:"../../image/friends.png",
                    name:"群聊(websocket的Demo)",
                    url:"../ws/ws"
                },
                {
                    img:"../../image/label.png",
                    name:"标签"
                },
                {
                    img:"../../image/friends_2.png",
                    name:"公众号"
                }
            ]
          },
          {
              text:"C",
              list_tool:[
                {
                    img:"../../image/ben.png",
                    name:"成凤杰"
                }
              ]
          },
          {
              text:"D",
              list_tool:[
                {
                    img:"../../image/perry.png",
                    name:"邓福滨"
                }
              ]
          },
          {
              text:"L",
              list_tool:[
                {
                    img:"../../image/max.png",
                    name:"梁雨"
                },
                {
                    img:"../../image/mike.png",
                    name:"廖芳樱"
                }
              ]
          },
          {
              text:"W",
              list_tool:[
                {
                    img:"../../image/adam.jpg",
                    name:"王浩"
                }
              ]
          }
      ]
    },
    goPage:function(e){
        var url = e.currentTarget.dataset.url;
        wx.navigateTo({
            url: url
        })
    }
})
