// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/shortid/shortid.d.ts
declare module "shortid" {
	export function generate(): string;
	export function characters(string: string): string;
	export function isValid(id: any): boolean;
	export function worker(integer: number): void;
	export function seed(float: number): void;
}
